import {
  AbsoluteFill,
  interpolate,
  spring,
  useCurrentFrame,
  useVideoConfig,
} from "remotion"

import { recapInputSchema, type RecapInput } from "./recap-data"

const WIDTH = 1280
const HEIGHT = 720

const formatCurrency = (n: number) =>
  `$${Math.round(n).toLocaleString("en-US")}`

function buildAreaPath(
  data: number[],
  reveal: number,
  width: number,
  height: number,
) {
  if (data.length === 0) return { line: "", area: "" }
  const max = Math.max(...data) * 1.1
  const visibleCount = Math.max(2, Math.ceil(data.length * reveal))
  const slice = data.slice(0, visibleCount)
  const step = width / (data.length - 1)

  const points = slice.map((v, i) => {
    const x = i * step
    const y = height - (v / max) * height
    return [x, y] as const
  })

  const line = points
    .map(([x, y], i) => `${i === 0 ? "M" : "L"} ${x.toFixed(2)} ${y.toFixed(2)}`)
    .join(" ")
  const lastX = points[points.length - 1][0]
  const area = `${line} L ${lastX.toFixed(2)} ${height} L 0 ${height} Z`
  return { line, area }
}

export const recapSchema = recapInputSchema

export const WeeklyRecap: React.FC<RecapInput> = ({
  rangeLabel,
  totalRevenue,
  revenueDelta,
  activeUsers,
  conversion,
  bestDay,
  revenueSeries,
  channels,
}) => {
  const frame = useCurrentFrame()
  const { fps } = useVideoConfig()

  const intro = spring({ frame, fps, config: { damping: 14 } })
  const titleY = interpolate(intro, [0, 1], [40, 0])
  const titleOpacity = interpolate(intro, [0, 1], [0, 1])

  const revenueProgress = spring({
    frame: frame - fps * 0.4,
    fps,
    config: { damping: 18, stiffness: 90 },
  })
  const revenueValue = interpolate(revenueProgress, [0, 1], [0, totalRevenue])

  const usersProgress = spring({
    frame: frame - fps * 0.7,
    fps,
    config: { damping: 18, stiffness: 90 },
  })
  const usersValue = interpolate(usersProgress, [0, 1], [0, activeUsers])

  const conversionProgress = spring({
    frame: frame - fps * 1.0,
    fps,
    config: { damping: 18, stiffness: 90 },
  })
  const conversionValue = interpolate(conversionProgress, [0, 1], [0, conversion])

  const chartReveal = interpolate(
    frame,
    [fps * 1.2, fps * 3.4],
    [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  )

  const { line, area } = buildAreaPath(revenueSeries, chartReveal, 800, 220)

  const totalChannels = channels.reduce((s, c) => s + c.value, 0) || 1
  const donutReveal = interpolate(
    frame,
    [fps * 2.0, fps * 4.2],
    [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  )

  const bestDayProgress = spring({
    frame: frame - fps * 4.4,
    fps,
    config: { damping: 12 },
  })
  const bestDayY = interpolate(bestDayProgress, [0, 1], [60, 0])

  const positive = revenueDelta >= 0

  return (
    <AbsoluteFill
      style={{
        background:
          "radial-gradient(ellipse at top, #1f2937 0%, #0b0f17 60%, #04060b 100%)",
        color: "white",
        fontFamily:
          "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
      }}
    >
      <AbsoluteFill
        style={{
          backgroundImage:
            "linear-gradient(to right, rgba(255,255,255,0.04) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,255,255,0.04) 1px, transparent 1px)",
          backgroundSize: "48px 48px",
        }}
      />

      <div
        style={{
          padding: 64,
          display: "flex",
          flexDirection: "column",
          gap: 40,
          height: "100%",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            opacity: titleOpacity,
            transform: `translateY(${titleY}px)`,
          }}
        >
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <span
              style={{
                fontSize: 18,
                letterSpacing: 4,
                textTransform: "uppercase",
                color: "rgba(255,255,255,0.55)",
              }}
            >
              Insights recap
            </span>
            <span style={{ fontSize: 44, fontWeight: 600 }}>{rangeLabel}</span>
          </div>
          <div
            style={{
              padding: "10px 18px",
              borderRadius: 999,
              background: "rgba(255,255,255,0.08)",
              fontSize: 16,
              letterSpacing: 1,
            }}
          >
            Generated by Remotion
          </div>
        </div>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1.4fr 1fr 1fr",
            gap: 24,
          }}
        >
          <div
            style={{
              background: "rgba(255,255,255,0.05)",
              borderRadius: 24,
              padding: 28,
              border: "1px solid rgba(255,255,255,0.08)",
              display: "flex",
              flexDirection: "column",
              gap: 12,
            }}
          >
            <span style={{ fontSize: 14, color: "rgba(255,255,255,0.6)" }}>
              Total revenue
            </span>
            <span
              style={{
                fontSize: 64,
                fontWeight: 600,
                fontVariantNumeric: "tabular-nums",
              }}
            >
              {formatCurrency(revenueValue)}
            </span>
            <span
              style={{
                display: "inline-flex",
                width: "fit-content",
                alignItems: "center",
                gap: 6,
                padding: "6px 12px",
                borderRadius: 999,
                fontSize: 14,
                fontWeight: 500,
                background: positive
                  ? "rgba(16,185,129,0.18)"
                  : "rgba(244,63,94,0.18)",
                color: positive ? "#34d399" : "#fb7185",
              }}
            >
              {positive ? "▲" : "▼"} {Math.abs(revenueDelta).toFixed(1)}% vs prior
            </span>
          </div>

          <div
            style={{
              background: "rgba(255,255,255,0.05)",
              borderRadius: 24,
              padding: 28,
              border: "1px solid rgba(255,255,255,0.08)",
              display: "flex",
              flexDirection: "column",
              gap: 8,
            }}
          >
            <span style={{ fontSize: 14, color: "rgba(255,255,255,0.6)" }}>
              Active users
            </span>
            <span
              style={{
                fontSize: 56,
                fontWeight: 600,
                fontVariantNumeric: "tabular-nums",
              }}
            >
              {Math.round(usersValue).toLocaleString()}
            </span>
            <span style={{ fontSize: 14, color: "rgba(255,255,255,0.45)" }}>
              People active in the period
            </span>
          </div>

          <div
            style={{
              background: "rgba(255,255,255,0.05)",
              borderRadius: 24,
              padding: 28,
              border: "1px solid rgba(255,255,255,0.08)",
              display: "flex",
              flexDirection: "column",
              gap: 8,
            }}
          >
            <span style={{ fontSize: 14, color: "rgba(255,255,255,0.6)" }}>
              Conversion
            </span>
            <span
              style={{
                fontSize: 56,
                fontWeight: 600,
                fontVariantNumeric: "tabular-nums",
              }}
            >
              {conversionValue.toFixed(2)}%
            </span>
            <span style={{ fontSize: 14, color: "rgba(255,255,255,0.45)" }}>
              Visitor → action
            </span>
          </div>
        </div>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1.6fr 1fr",
            gap: 24,
            flex: 1,
          }}
        >
          <div
            style={{
              background: "rgba(255,255,255,0.05)",
              borderRadius: 24,
              padding: 28,
              border: "1px solid rgba(255,255,255,0.08)",
              display: "flex",
              flexDirection: "column",
              gap: 16,
              position: "relative",
              overflow: "hidden",
            }}
          >
            <div
              style={{ display: "flex", alignItems: "baseline", gap: 12 }}
            >
              <span
                style={{ fontSize: 18, color: "rgba(255,255,255,0.7)" }}
              >
                Revenue trend
              </span>
              <span
                style={{ fontSize: 12, color: "rgba(255,255,255,0.4)" }}
              >
                {revenueSeries.length} data points
              </span>
            </div>
            <svg
              viewBox="0 0 800 240"
              style={{ width: "100%", height: 240 }}
            >
              <defs>
                <linearGradient id="recapArea" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor="#60a5fa" stopOpacity="0.55" />
                  <stop offset="100%" stopColor="#60a5fa" stopOpacity="0" />
                </linearGradient>
              </defs>
              {[0.25, 0.5, 0.75].map((p) => (
                <line
                  key={p}
                  x1={0}
                  x2={800}
                  y1={220 * p}
                  y2={220 * p}
                  stroke="rgba(255,255,255,0.08)"
                  strokeDasharray="4 6"
                />
              ))}
              <path d={area} fill="url(#recapArea)" />
              <path
                d={line}
                fill="none"
                stroke="#60a5fa"
                strokeWidth={3}
                strokeLinejoin="round"
                strokeLinecap="round"
              />
            </svg>

            <div
              style={{
                position: "absolute",
                bottom: 28,
                right: 28,
                display: "flex",
                flexDirection: "column",
                alignItems: "flex-end",
                gap: 4,
                opacity: bestDayProgress,
                transform: `translateY(${bestDayY}px)`,
              }}
            >
              <span
                style={{ fontSize: 12, color: "rgba(255,255,255,0.5)" }}
              >
                Best day
              </span>
              <span
                style={{
                  fontSize: 28,
                  fontWeight: 600,
                  fontVariantNumeric: "tabular-nums",
                }}
              >
                {bestDay.label} · {bestDay.value.toLocaleString()}
              </span>
            </div>
          </div>

          <div
            style={{
              background: "rgba(255,255,255,0.05)",
              borderRadius: 24,
              padding: 28,
              border: "1px solid rgba(255,255,255,0.08)",
              display: "flex",
              flexDirection: "column",
              gap: 16,
            }}
          >
            <span style={{ fontSize: 18, color: "rgba(255,255,255,0.7)" }}>
              Channels
            </span>
            <div
              style={{
                position: "relative",
                width: "100%",
                aspectRatio: "1 / 1",
              }}
            >
              <svg
                viewBox="0 0 200 200"
                style={{ width: "100%", height: "100%", transform: "rotate(-90deg)" }}
              >
                <circle
                  cx={100}
                  cy={100}
                  r={80}
                  fill="none"
                  stroke="rgba(255,255,255,0.08)"
                  strokeWidth={20}
                />
                {(() => {
                  const r = 80
                  const c = 2 * Math.PI * r
                  return channels.reduce<{
                    nodes: React.ReactNode[]
                    offset: number
                  }>(
                    (state, ch) => {
                      const portion = ch.value / totalChannels
                      const dash = portion * c * donutReveal
                      state.nodes.push(
                        <circle
                          key={ch.label}
                          cx={100}
                          cy={100}
                          r={r}
                          fill="none"
                          stroke={ch.color}
                          strokeWidth={20}
                          strokeDasharray={`${dash} ${c - dash}`}
                          strokeDashoffset={-state.offset}
                        />,
                      )
                      return {
                        nodes: state.nodes,
                        offset: state.offset + portion * c,
                      }
                    },
                    { nodes: [], offset: 0 },
                  ).nodes
                })()}
              </svg>
              <div
                style={{
                  position: "absolute",
                  inset: 0,
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                <span style={{ fontSize: 13, color: "rgba(255,255,255,0.5)" }}>
                  Sessions
                </span>
                <span
                  style={{
                    fontSize: 32,
                    fontWeight: 600,
                    fontVariantNumeric: "tabular-nums",
                  }}
                >
                  {Math.round(totalChannels * donutReveal).toLocaleString()}
                </span>
              </div>
            </div>
            <ul
              style={{
                display: "grid",
                gridTemplateColumns: "1fr 1fr",
                gap: 8,
                listStyle: "none",
                padding: 0,
                margin: 0,
                fontSize: 13,
              }}
            >
              {channels.map((ch) => (
                <li
                  key={ch.label}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 8,
                    color: "rgba(255,255,255,0.7)",
                  }}
                >
                  <span
                    style={{
                      width: 10,
                      height: 10,
                      borderRadius: 999,
                      background: ch.color,
                    }}
                  />
                  <span style={{ flex: 1 }}>{ch.label}</span>
                  <span style={{ fontVariantNumeric: "tabular-nums" }}>
                    {((ch.value / totalChannels) * 100).toFixed(0)}%
                  </span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </AbsoluteFill>
  )
}

export const RECAP_DURATION_FRAMES = 180
export const RECAP_FPS = 30
export const RECAP_WIDTH = WIDTH
export const RECAP_HEIGHT = HEIGHT
